apiVersion: v1
kind: Service
metadata:
  name: {{ include "probe-manager.fullname" . }}-admin
  labels:
    app: admin
    {{- include "probe-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: 8081
      protocol: TCP
  selector:
    app: admin
