apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "probe-manager.fullname" . }}-admin
  labels:
    app: admin
    {{- include "probe-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.global.imageRegistry }}{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            {{- range $key, $value := .Values.admin.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.admin.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
