apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "probe-manager.fullname" . }}-agent
  labels:
    app: agent
    {{- include "probe-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: "{{ .Values.global.imageRegistry }}{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          ports:
            - containerPort: 58081
          env:
            {{- range $key, $value := .Values.agent.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: 58081
            initialDelaySeconds: 30
            periodSeconds: 15
