apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "probe-manager.fullname" . }}-web
  labels:
    app: web
    {{- include "probe-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.global.imageRegistry }}{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
